# Generated by Django 4.2.16 on 2026-05-09 20:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=6, unique=True)),
                ('host_username', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('bidding', 'Bidding'), ('playing', 'Playing'), ('finished', 'Finished')], default='waiting', max_length=20)),
                ('num_decks', models.PositiveSmallIntegerField(default=1)),
                ('current_round', models.PositiveSmallIntegerField(default=0)),
                ('max_rounds', models.PositiveSmallIntegerField(default=0)),
                ('trump_suit', models.CharField(blank=True, max_length=10)),
                ('current_player_index', models.PositiveSmallIntegerField(default=0)),
                ('lead_player_index', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('seat', models.PositiveSmallIntegerField()),
                ('hand', models.JSONField(default=list)),
                ('bid', models.SmallIntegerField(default=-1)),
                ('tricks_won', models.PositiveSmallIntegerField(default=0)),
                ('total_score', models.IntegerField(default=0)),
                ('is_connected', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='game.game')),
            ],
            options={
                'ordering': ['seat'],
                'unique_together': {('game', 'seat'), ('game', 'username')},
            },
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('trump_suit', models.CharField(max_length=10)),
                ('cards_per_player', models.PositiveSmallIntegerField()),
                ('is_complete', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='game.game')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Trick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('lead_suit', models.CharField(blank=True, max_length=10)),
                ('is_complete', models.BooleanField(default=False)),
                ('round', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tricks', to='game.round')),
                ('winner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tricks_won_set', to='game.player')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='TrickCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suit', models.CharField(max_length=10)),
                ('rank', models.CharField(max_length=2)),
                ('deck_id', models.PositiveSmallIntegerField(default=1)),
                ('play_order', models.PositiveSmallIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player')),
                ('trick', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='game.trick')),
            ],
            options={
                'ordering': ['play_order'],
            },
        ),
    ]
