# Generated by Django 4.2.16 on 2026-05-10 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_teams_and_expected_players'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='start_round',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
