# Generated by Django 4.2.16 on 2026-05-25 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_game_start_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='trump_card',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='round',
            name='trump_card',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
