# Generated by Django 4.2.16 on 2026-05-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_game_trump_card_round_trump_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('bidding', 'Bidding'), ('playing', 'Playing'), ('finished', 'Finished'), ('prompt', 'Prompt')], default='waiting', max_length=20),
        ),
    ]
